(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g=this||self;function h(a){if(a&&a!=g)return m(a.document);null===p&&(p=m(g.document));return p}var q=/^[\w+/_-]+[=]{0,2}$/,p=null;function m(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&q.test(a)?a:""}var r="closure_uid_"+(1E9*Math.random()>>>0),t=0;function u(a){return a}
function v(a){var b=null,c=g.trustedTypes;if(!c||!c.createPolicy)return b;try{b=c.createPolicy(a,{createHTML:u,createScript:u,createScriptURL:u})}catch(e){g.console&&g.console.error(e.message)}return b};var x;function y(){var a=z;return function(){var b=this||g;b=b.closure_memoize_cache_||(b.closure_memoize_cache_={});var c=Object.prototype.hasOwnProperty.call(v,r)&&v[r]||(v[r]=++t);c=a(c,arguments);return b.hasOwnProperty(c)?b[c]:b[c]=v.apply(this,arguments)}}function z(a,b){a=[a];for(var c=b.length-1;0<=c;--c)a.push(typeof b[c],b[c]);return a.join("\x0B")};function A(a,b){this.h=a===B&&b||"";this.g=C}var C={},B={};try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){};function D(a){this.g=a||g.document||document};function E(a,b,c){a.timeOfStartCall=(new Date).getTime();var e=c||g,n=e.document,d=a.nonce||h(e);d&&!a.nonce&&(a.nonce=d);if("help"==a.flow){a:{var f=["document","location","href"];for(var l=e||g,w=0;w<f.length;w++)if(l=l[f[w]],null==l){f=null;break a}f=l}!a.helpCenterContext&&f&&(a.helpCenterContext=f.substring(0,1200));f=!0;b&&JSON&&JSON.stringify&&(l=JSON.stringify(b),(f=1200>=l.length)&&(a.psdJson=l));f||(b={invalidPsd:!0})}b=[a,b,c];e.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.serverUri||"//www.google.com/tools/feedback";
if(f=e.GOOGLE_FEEDBACK_START)f.apply(e,b);else{e=c+"/load.js?";for(var k in a)b=a[k],(c=null==b)||(c=typeof b,c="object"==c&&null!=b||"function"==c),c||(e+=encodeURIComponent(k)+"="+encodeURIComponent(b)+"&");a=(n?new D(9==n.nodeType?n:n.ownerDocument||n.document):x||(x=new D)).g;k="SCRIPT";"application/xhtml+xml"===a.contentType&&(k=k.toLowerCase());a=a.createElement(k);d&&a.setAttribute("nonce",d);d=e;d=(k=y()("uf-api#html"))?k.createScriptURL(d):d;d=new A(B,d);a.src=d instanceof A&&d.constructor===
A&&d.g===C?d.h:"type_error:TrustedResourceUrl";(d=h(a.ownerDocument&&a.ownerDocument.defaultView))&&a.setAttribute("nonce",d);n.body.appendChild(a)}}var F=["userfeedback","api","startFeedback"],G=g;F[0]in G||"undefined"==typeof G.execScript||G.execScript("var "+F[0]);for(var H;F.length&&(H=F.shift());)F.length||void 0===E?G[H]&&G[H]!==Object.prototype[H]?G=G[H]:G=G[H]={}:G[H]=E;}).call(this);
